#!/bin/bash
# Script for designing binders to EGFR, targeting specific epitope residues

# Define the output path and input pdb of the target protein (EGFR)
output_prefix="example_outputs/egfr_binder_design"
input_pdb="input_pdbs/8hgo_egfr.pdb"  # Path to your EGFR extracellular domain structure

# Specify the contig input:
# - Residues 1-150 of the A chain of the target protein (EGFR) to be used for initial binding proximity
# - A chain break to ensure the binder is not fused to the target
# - A 70-100 residue binder segment to be generated by diffusion
# Targeted epitope residues: 349, 350, 353, 354, 384, 385, 417, 418, 419, 441, 442, 467, 468, and 469

../scripts/run_inference.py \
    inference.output_prefix=$output_prefix \
    inference.input_pdb=$input_pdb \
    'contigmap.contigs=[A30-480/0 50-150]' \
    'ppi.hotspot_res=[A35,A36,A37,A39,A40,A41,A42]' \
    inference.num_designs=600 \
    denoiser.noise_scale_ca=0 \
    denoiser.noise_scale_frame=0 
    #inference.ckpt_override_path=../models/Complex_beta_ckpt.pt
